### ISSUE TITLE
Not able to compile eospin contracts on arm64 machines

### ISSUE THREAD

**Issue by AstroWa3l** [ImperatorLang/eopsin#17]
I was not able to compile a script on my MacBook due to it being arm64 architecture, I think there is a way to work around this but not 100%. I am going to try to see what libraries are causing issues and find a solution. A simple solution of course is using a VM or something but rather try to see if there is a simple fix first.

Error:
```
ImportError: dlopen(/opt/homebrew/lib/python3.8/site-packages/_cffi_backend.cpython-38-darwin.so, 0x0002): tried: '/opt/homebrew/lib/python3.8/site-packages/_cffi_backend.cpython-38-darwin.so
```

**Comment by nielstron** [comment]
Might be that pyaiken does not work on Mac yet. You can try compiling using the section "Deploying via aiken" from the README

**Comment by nielstron** [comment]
Which command did you try?

**Comment by nielstron** [comment]
I set up bug report templates. If you don't mind please reopen the issue as Bug Report and fill out the details so that I can try to reproduce the issue.

**Comment by AstroWa3l** [comment]
No problem, and thank you!!!
