### ISSUE TITLE
optimize module missing in pip install

### ISSUE THREAD

**Issue by reitcircles** [ImperatorLang/eopsin#27]
**Describe the bug**
Just installed eopsin in ubuntu and optimize directory is missing. 

**To Reproduce**
Just follow the standard eopsin install as mentioned in https://pycardano.readthedocs.io/en/latest/guides/plutus.html

python3.8 -m venv venv
source venv/bin/activate
pip install eopsin-lang

**Expected behavior**
eopsin is installed. But now browse to the directory:

env/lib/python3.8/site-packages/eopsin
And one would expect the directory "Optimize" to be present. But it is missing. 
Resulting in error during compilation: ModuleNotFoundError: No module named 'eopsin.optimize'

**Comment by nielstron** [comment]
Thanks for the heads up! This should be fixed in version 0.5.2 which I just released
