### ISSUE TITLE
gift.py sample compilation error

### ISSUE THREAD

**Issue by reitcircles** [ImperatorLang/eopsin#49]
**Describe the bug**

**To Reproduce**
1. in documentation page under smart contract there is file gift.py
2. Follow instruction to install eopsin-lang
3. Build fails:
4. `ImportError: cannot import name 'CompilingNodeTransformer' from 'eopsin.util' `

**Expected behavior**
Should have a clean build

** Operating system**
output of uname -a;
Linux nft-srv-1 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by nielstron** [comment]
what version of Eopsin are you using?

`pip freeze | grep eopsin`

**Comment by nielstron** [comment]
Please also provide the exact sequence of commands that lead to this error. Based on your description, I can not reproduce the issue

**Comment by reitcircles** [comment]
ok. I replicated with python3.8 and seems to work. Kindly updated the main documentation .... it is really annoying. thanks.

**Comment by nielstron** [comment]
Got it. Should not allow being installed with a different python version anymore until explicitly supported.
