### ISSUE TITLE
GitHub Releases

### ISSUE THREAD

**Issue by juliusfrost** [ImperatorLang/eopsin#61]
**Is your feature request related to a problem? Please describe.**
At the moment, it's only possible to track new changes in releases through git commits. For a rapidly changing and improving project like eopsin, it makes this more challenging.

**Describe the solution you'd like**
It would be nice to add GitHub releases with descriptions for added transparency.

**Describe alternatives you've considered**
Pypi is the main source to notify users of updates, but doesn't support release summaries.

**Additional context**
Thanks for actively working on this! Right now I'm following the fourth iteration of the plutus-pioneer-program and implementing it in eopsin.

**Comment by nielstron** [comment]
Thanks for the feedback. Due to limited resources, I have for now resorted to using tags for tagging release commits, annotating the tag commits with a short write-up of included changes

You can check them here
https://github.com/ImperatorLang/eopsin/tags

I will try to add releases as time permits

**Comment by nielstron** [comment]
I at some point disabled showing releases on the main page but since they are a thing now I have re-added them. Also, creating a release off a tag is not much effort so I might as well write some up (with high level details)

**Comment by juliusfrost** [comment]
> I at some point disabled showing releases on the main page but since they are a thing now I have re-added them. Also, creating a release off a tag is not much effort so I might as well write some up (with high level details)

Awesome thanks!

**Comment by nielstron** [comment]
Btw @juliusfrost please consider sharing some sample contracts along written along with the plutus pioneer program. Maybe the eopsin-pioneer-program? :D
